# Config file for automatic testing at travis-ci.com
dist: focal
language: python
python: 3.8

before_install:
    - sudo apt-get update
    - sudo apt -y install libgeos-dev

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script:
    - tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
#before_deploy:
#  # Set up git user name and tag this commit
#  - git config --local user.name floschl
#  - git config --local user.email 1262767+floschl@users.noreply.github.com
#  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#  - git tag $TRAVIS_TAG
deploy:
  - provider: releases
    api_key:
      secure: "sj3ZJp5uG173+7cPCRzT0B2xBs7wsYrwyHFmac6xsFzJMsWiqijp/m+D+W68cbQJtkz5QHQtvjU1UJeFxrndyOqfoA7jcWAbAmE8LIzbp588gnvJaey0xiNx1EzVnI61SJSyOTe1QwYxR7w9GFdEzGkwvY5suHbznJwPgWt/Ltr66oJtzu+1mlGhwLoTz3+xmElwvTnIvgE5uVDJQQGKjf8UweTxb6tR+olGPETHDM1xl1wtLKIjKmi5LocES5pigHjLSUJZqP4unrDtwlCZst3tU9KwksKilAXWJ4gBJWbuYwQQ5EFoAmZTmkwEPDMLHGlQA6ZodtiJoBAVdAFun2PJ/oZm5r+0ytZQz5DqEs5KdTuDM7PWVPG35M22V38EREloRsXhkjOOCwR80by5g+evMD6qoyc7DFMkToyT0lVUU9UdSsDAOug0RXsijhaDmADZ9adBQwIQpWRsawkzQeNTYxFvKeIR9eMyxGRHVchqzFySFvmEh/nEg1OJh56400Uy9xx5sMJCbXKoR/JRn6S0zx3cr1iUSPGlCjbHy9GYU1xJ2EKhdp0kiVCUJSgfawH9ZWdIT2CBYvXPS3uwcVKVLRk4Iy1DaTuhTZTgwp5DL6rlErgoH6h2w0yvTImNLKAL+TO38OnpKLuX6PgFq1D6Ji/64y3bHlK+UpfQpL8="
#    draft: true
    skip_cleanup: true
    on:
      tags: true
      branch: main
      python: 3.8
  - provider: pypi
    distributions: sdist bdist_wheel
    username: "__token__"
    password:
        secure: "ebk3b2hc7ocKtmL93ICXbqMMMEgWBde1xl3rk63KqArS0+1Vv96LhC6+OdBfvw4o4sQ1Da39EM6sRdXgxqRsER7rkKW+OcRLGnkkKD2XsBjDhcTVhBRMh+O1vRwVBlKqGYXIbH9VkvI+iG1p0RHEzmWHNFRH0gS74smewp4axyeGRziSeVfRLi4fKo577uE+mTpKo7Y/NKdccNTt330/LR5ctVW6njpObNojJsCIDSME6KNC1iIErmg79PcX5LAPbkFsYpDtbJodqD6QjetHB54tgauz5zNqauK0ivtZGCWbwFbzcJbF5pxM1J3BXi6vQKP9YIb5gtR/xo8Ii0y8Gl0wHRk8f1oKFwnBUeU5NXF7Y7Vkg4x1yuNnfqXGwBiSeEqSJxa+j4vUdmanHUYebSyNZ/bvN02pA7gZyAoyQGIGenh6xQ06TpNI9QDAtpgX/wWGSxTIb7C3UBnl31Jkd1XsscOybXxUHp/vdh6w2MmxSNa7PDuAsGSDt5yLF8yr3PVNXW+mjkuPV0Kumyk+GXI2+0yxmVirdQm5OsOE/Plg8EDIPmwWcMoA32e7l9Z+7al5xGm60pt2d0lYSIDyBeQyL3zRkme0ZdTWBhDIGApOkKSABHzPR7gwxazt6Jvl8vXcktaABJQ9/MMSsxfrjpH53PyjSJEjhJoTEzRo25w="
    on:
      tags: true
      python: 3.8
