name: ci
on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
#        python-version: ["3.8", "3.11"]
        python-version: ["3.8"]
    steps:
      - name: Install Geos (Linux)
        run: sudo apt -y install libgeos-dev
      - name: Test Py ${{ matrix.python-version }}
        uses: collective/tox-action@main
        with:
          python-version: ${{ matrix.python-version }}

  build:
    runs-on: "ubuntu-latest"
#    environment:
#      name: pypi
#      url: https://pypi.org/p/pysamosa
#    permissions:
#      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install build dependencies
        run: python -m pip install -r requirements.txt

      - name: Install build dependencies
        run: python -m pip install build wheel

      - name: Build extensions
        run: python setup.py build_ext --inplace

      - name: Build distributions
        shell: bash -l {0}
        run: python setup.py sdist bdist_wheel
